version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: friday
    groups:
      codeql-actions:
        patterns:
          - "github/codeql-action/*"

  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
      day: friday
    groups:
      microsoft-extensions-configuration:
        patterns:
          - "Microsoft.Extensions.Configuration.*"
