name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release (${{ matrix.runtime }})
    runs-on: windows-latest
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        runtime: [ win-x64 ]

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore -r ${{ matrix.runtime }}

      - name: Publish
        run: dotnet publish -r ${{ matrix.runtime }} -p:PublishProfile=FolderProfile -p:PublishDir=publish --no-restore

      - name: Package
        run: |
          $releaseDir = "./release"
          New-Item -ItemType Directory -Path $releaseDir

          Get-ChildItem -Directory | ForEach-Object {
            $publishDir = "./$($_.Name)/publish"

            if (Test-Path $publishDir) {
              Write-Host "Copy: $publishDir -> $releaseDir"
              Copy-Item -Path "$publishDir/*" -Destination $releaseDir -Force
            }
          }

          Copy-Item -Path LICENSE -Destination "$releaseDir/LICENSE.txt"
          Copy-Item -Path ThirdPartyNotices.md -Destination $releaseDir

          Compress-Archive -Path "$releaseDir/*" -DestinationPath ${{ github.event.repository.name }}-${{ matrix.runtime }}.zip

      - name: Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          files: ${{ github.event.repository.name }}-${{ matrix.runtime }}.zip
